<a href="https://colab.research.google.com/github/benram2004-lab/mis433/blob/main/Copy_of_assignment_python_basics.week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [2]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? ben
Welcome, ben!


In [3]:
f = float(input('Please enter the temperature in Fahrenheit: '))

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')

Please enter the temperature in Fahrenheit: 53
53.0F is 11.666666666666666 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [4]:
# complete your program here
f=float(input('Please enter the temperature in Celcius: '))

c=(f*9/5)+32

print(f'{f}C is {c} in Fahrenheit. ')

Please enter the temperature in Celcius: 53
53.0C is 127.4 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [9]:
# complete your program here
d_str = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

temp = float(d_str)

# Formula: Celsius/5 = (Fahrenheit - 32)/9

if m.lower() == 'c' or m.lower() == 'celsius':
    converted_temp = (temp * 9/5) + 32
    print(f'{temp}C is {converted_temp} in Fahrenheit')
elif m.lower() == 'f' or m.lower() == 'fahrenheit':
    converted_temp = (temp - 32) * 5/9
    print(f'{temp}F is {converted_temp} in Celsius')
else:
    print('Invalid unit. Please enter C for Celsius or F for Fahrenheit.')


Please enter the temperature: 23
Is this in Celsius or Fahrenheit? Celsius
23.0C is 73.4 in Fahrenheit


## Question 2

Have some fun with strings.

In [13]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [14]:
# Find the length of this sentence.
len(sentence)

48

In [15]:
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [16]:
# Extract a substring from the 10th character from left to the 10th character from right.

print(sentence[9:len(sentence)-9])

heap. Show me the code - Linus


In [17]:
# Split the sentence into a list of substrings by space ' '.
words = sentence.split(' ')
print(words)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [18]:
import string

# Convert to lowercase
lower_sentence = sentence.lower()

# Remove punctuation
translator = str.maketrans('', '', string.punctuation)
cleaned_sentence = lower_sentence.translate(translator)

# Split into words
words_no_punctuation = cleaned_sentence.split()
print(words_no_punctuation)

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [19]:
# Count the total number of vowels in the sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
vowels = 'aeiou'
count = 0
for v in vowels:
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"The total number of vowel is {count}")

a 3
e 4
i 2
o 3
u 1
The total number of vowel is 13


In [20]:
# Find the positions (indexes) of all vowels in the sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
vowels = 'aeiou'
vowel_positions = []
for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
        vowel_positions.append(i)
print(vowel_positions)

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [21]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [22]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
print(cubes_lc)

[0, 1, 8, 27, 64]


In [23]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'
vowel_positions_lc = [i for i, char in enumerate(sentence) if char.lower() in vowels]
print(vowel_positions_lc)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [24]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n= int(n)

# add your code here
if n==1:
  fibonacci = [0]
elif n== 2:
  fibonacci = [0,1]
else:
  fibonacci = [0,1]
  while len(fibonacci)<n:
    fibonacci.append(fibonacci[-1]+fibonacci[-2])
print(fibonacci)


How many numbers do you want? 32
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [25]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {"Pfizer": .95,
          "Moderna": .95,
          "AstraZeneca": .72,
          "Johnson & Johnson": .66}
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [27]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine

print(f"The efficacy of {v} is {v_dict[v]}")

Which vaccine? Pfizer
The efficacy of Pfizer is 0.95


In [28]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [29]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [30]:
# Print vaccines with efficacy lower than 90%.

for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(f'{vaccine}: {efficacy*100:.2f}%')

AstraZeneca: 72.00%
Johnson & Johnson: 66.00%
Sinovac: 50.38%


In [31]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [32]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
for char in sentence:
    if char != ' ':
        ch_dict[char] = ch_dict.get(char, 0) + 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [33]:
import numpy as np

In [34]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
even_numbers = np.arange(2, 41, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [35]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
odd_numbers = np.arange(1, 40, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [36]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
array_10x10 = np.arange(100).reshape(10, 10)
print(array_10x10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [37]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, size=(10, 10))
M.shape

(10, 10)

In [38]:
# Count the numbers in M with an absolute value greater than 1.
count_greater_than_1 = np.sum(np.abs(M) > 1)
print(f"Number of elements in M with absolute value greater than 1: {count_greater_than_1}")

Number of elements in M with absolute value greater than 1: 28


In [39]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

r = int(r)
c = int(c)

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
arr

Row count: 54
column count: 32


array([[19, 15, 14, ..., 19, 14, 12],
       [11, 18, 17, ..., 10, 18, 16],
       [14, 19, 12, ..., 18, 16, 15],
       ...,
       [11, 18, 11, ..., 16, 16, 19],
       [11, 15, 12, ..., 19, 15, 17],
       [18, 10, 16, ..., 11, 11, 11]])

In [40]:
# output the element in the first row and the third column
print(arr[0, 2])

14


In [41]:
# output the element in the second row and the last column
print(arr[1, -1])

16


In [42]:
# output the second row of the array
print(arr[1])

[11 18 17 15 18 12 13 17 13 10 17 10 18 16 13 12 10 14 12 12 15 18 12 15
 11 18 16 10 12 10 18 16]


In [43]:
print(arr[-2])

[11 15 12 14 15 18 10 13 15 17 10 13 18 10 10 11 14 17 17 12 18 18 16 16
 16 18 17 10 13 19 15 17]


In [45]:
# output the second column of the array
print(arr[:, 1])

[15 18 19 10 16 15 12 17 18 18 13 17 16 16 19 15 12 13 19 11 13 10 12 17
 11 18 18 14 14 17 11 15 18 10 13 19 12 14 14 17 15 12 15 15 16 12 18 12
 17 13 17 18 15 10]


In [46]:
# output the second column of the array
print(arr[:, 1])

[15 18 19 10 16 15 12 17 18 18 13 17 16 16 19 15 12 13 19 11 13 10 12 17
 11 18 18 14 14 17 11 15 18 10 13 19 12 14 14 17 15 12 15 15 16 12 18 12
 17 13 17 18 15 10]


In [47]:
# output the second last column of the array
print(arr[:, -2])

[14 18 16 11 17 11 18 19 18 16 19 13 13 11 18 19 19 12 10 15 19 14 10 18
 18 19 17 16 18 17 17 15 11 15 17 17 16 17 13 13 13 11 17 13 19 13 14 16
 18 18 15 16 15 11]


In [48]:
# output the upper-left 3x3 sub-array
print(arr[:3, :3])

[[19 15 14]
 [11 18 17]
 [14 19 12]]


In [49]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[11 18 11]
 [11 15 12]
 [18 10 16]]


In [50]:
# output the upper-right 3x3 sub-array
print(arr[:3, -3:])

[[19 14 12]
 [10 18 16]
 [18 16 15]]


In [51]:
# output the bottom-right 3x3 sub-array
print(arr[-3:, -3:])

[[16 16 19]
 [19 15 17]
 [11 11 11]]


In [52]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [53]:
# add a row [51,...,60] to A
new_row = np.arange(51, 61)
A = np.vstack([A, new_row])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [54]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.vsplit(A, 2)
print('A1:\n', A1)
print('A2:\n', A2)

A1:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
A2:
 [[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [55]:
# Add 10 to each element of A
A_plus_10 = A + 10
print(A_plus_10)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [56]:
# Calculate the square root of each element in A
A_sqrt = np.sqrt(A)
print(A_sqrt)

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]]


In [57]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [58]:
# Print the mean, standard deviation of all numbers in M
print(f"Mean of M: {np.mean(M)}")
print(f"Standard deviation of M: {np.std(M)}")

Mean of M: -0.1251416518333243
Standard deviation of M: 1.002772553920455


In [59]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f"Maximum of M: {np.max(M)}")
print(f"3rd Quartile of M: {np.percentile(M, 75)}")
print(f"Median of M: {np.median(M)}")
print(f"1st Quartile of M: {np.percentile(M, 25)}")
print(f"Minimum of M: {np.min(M)}")

Maximum of M: 2.27850001811315
3rd Quartile of M: 0.6229728927223119
Median of M: -0.09447384295643113
1st Quartile of M: -0.7881132401503905
Minimum of M: -3.45032732125481
